name: antidote-jiratodropbox
services:
- environment_slug: python
  github:
    branch: master
    deploy_on_push: true
    repo: https://github.com/finominal/antidoteJiraToDropbox
  name: antidote-jiratodropbox